### PR TITLE
Print test errors when they exists

### PR DESCRIPTION
**Pull request by thiagocaiubi**
Instead of just printing the summary it prints the test error output.

### CODE REVIEW

**Comment by gotwarlost** [comment]
Thanks for the pull request. I'm under a bit of deadline pressure right now but I will definitely look it over during the weekend. Thanks again!

**Comment by gotwarlost** [comment]
Hey, so I don't understand what exactly you are trying to do here. The error details are printed at the end of the run even without your patch here: 

https://github.com/chaordic/ytestrunner/blob/a36ad3858104412f8d782cbd651bcb928f489f59/lib/cli.js#L395

The only difference I saw with and without your pull request is that additional error blocks are printed in red. There is no extra information (except the red color) provided by your patch.

Could you explain what you are trying to accomplish?

**Comment by thiagocaiubi** [comment]
For some reason the output for me is this one:

https://github.com/chaordic/ytestrunner/commit/9a7fd464a588f634cb87d45ebe534965d897b988

I will investigate in more details soon.

Thanks!

**Comment by gotwarlost** [comment]
Basically, this is the bottom line.

You should either have:
1.  both ytestrunner as well as yuitest globally installed and not have them as devDependencies in your package.json
2. both of them as devDependencies in package.json and neither installed globally

Option (2) is preferred since these packages are clearly devDependencies, and give you the choice of having different versions of these libraries in different projects. In this case, you would use `npm test` to test your package and not the `ytestrunner` command directly.

**Pull request closed without merging**
